apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: harislukman/discovery-server:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761